export const ADD_IMAGES = 'ADD_IMAGES';
export const CHANGE_CAROUSEL_IMAGE = 'CHANGE_CAROUSEL_IMAGE';
export const CHANGE_INFO_PANEL_INDEX = 'CHANGE_INFO_PANEL_INDEX';
export const SET_MODAL_ACTIVATION = 'SET_MODAL_ACTIVATION';
export const SET_SELECTED_BLOG_INDEX = 'SET_SELECTED_BLOG_INDEX';
export const UPDATE_CODEMIRROR_CONTENT = 'UPDATE_CODEMIRROR_CONTENT';
export const SET_JS_FRAMEWORK = 'SET_JS_FRAMEWORK';
export const DEACTIVATE_DEMO = 'DEACTIVATE_DEMO';

export const RECEIVE_BLOG_ENTIRES = 'RECEIVE_BLOG_ENTIRES';
export const RECEIVE_BLOG_SUMMARIES = 'RECEIVE_BLOG_SUMMARIES';
export const RECEIVE_BLOG_IMAGES = 'RECEIVE_BLOG_IMAGES';
export const RECEIVE_BLOG_MINI_IMAGES = 'RECEIVE_BLOG_MINI_IMAGES';
export const RECEIVED_CAROUSEL_IMAGES = 'RECEIVED_CAROUSEL_IMAGES';
export const RECEIVED_PANEL_INFO = 'RECEIVED_PANEL_INFO';
export const RECEIVE_SAMPLE_CODE_INFO = 'RECEIVE_SAMPLE_CODE_INFO';

export const EDIT_PAGE = 'EDIT_PAGE';
export const SET_EDITED_CONTENT = 'SET_EDITED_CONTENT';
