export const ADD_IMAGES = 'ADD_IMAGES';
export const CHANGE_CAROUSEL_IMAGE = 'CHANGE_CAROUSEL_IMAGE';
export const CHANGE_INFO_PANEL_INDEX = 'CHANGE_INFO_PANEL_INDEX';
export const SET_MODAL_ACTIVATION = 'SET_MODAL_ACTIVATION';
export const SET_SELECTED_BLOG_INDEX = 'SET_SELECTED_BLOG_INDEX';
export const UPDATE_CODEMIRROR_CONTENT = 'UPDATE_CODEMIRROR_CONTENT';
export const SET_JS_FRAMEWORK = 'SET_JS_FRAMEWORK';
export const DEACTIVATE_DEMO = 'DEACTIVATE_DEMO';
